-- SamSa Database Schema
-- 1. Profiles Table (Extends Supabase Auth)
CREATE TABLE profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    phone_number TEXT,
    role TEXT DEFAULT 'CUSTOMER',
    -- CUSTOMER, COLLECTOR, ADMIN
    avatar_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- 2. Trash Vehicles (Pricing & Fleet)
CREATE TABLE trash_vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    capacity TEXT,
    price_ghs NUMERIC NOT NULL,
    description TEXT,
    icon TEXT,
    vehicle_type TEXT -- TRICYCLE, MINI_TRUCK, LARGE_TRUCK
);
-- 3. Pickup Requests
CREATE TABLE pickups (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id UUID REFERENCES profiles(id),
    collector_id UUID REFERENCES profiles(id),
    status TEXT DEFAULT 'PENDING',
    -- PENDING, ASSIGNED, COLLECTED, CANCELLED
    trash_type TEXT,
    vehicle_id BIGINT REFERENCES trash_vehicles(id),
    pickup_location_name TEXT,
    pickup_address TEXT,
    lat NUMERIC,
    lng NUMERIC,
    pricing_ghs NUMERIC,
    scheduled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- 4. Subscriptions
CREATE TABLE subscriptions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES profiles(id),
    plan_name TEXT,
    -- Weekly, Monthly
    status TEXT DEFAULT 'ACTIVE',
    expiry_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- ROW LEVEL SECURITY (RLS) policies
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE trash_vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pickups ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
-- Profiles: Anyone can read profiles (needed for dashboard), but only owner can edit.
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR
SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR
UPDATE USING (auth.uid() = id);
-- Trash Vehicles: Publicly viewable.
CREATE POLICY "Vehicles are viewable by everyone" ON trash_vehicles FOR
SELECT USING (true);
-- Pickups: 
-- 1. Customers can see/create their own requests.
-- 2. Collectors can see assigned or pending requests.
-- 3. Admins can see everything.
CREATE POLICY "Customers can view own pickups" ON pickups FOR
SELECT USING (auth.uid() = customer_id);
CREATE POLICY "Customers can create pickups" ON pickups FOR
INSERT WITH CHECK (auth.uid() = customer_id);
CREATE POLICY "Collectors can view pending/assigned pickups" ON pickups FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM profiles
            WHERE profiles.id = auth.uid()
                AND profiles.role IN ('COLLECTOR', 'ADMIN')
        )
    );
CREATE POLICY "Collectors can update assigned pickups" ON pickups FOR
UPDATE USING (
        collector_id = auth.uid()
        OR EXISTS (
            SELECT 1
            FROM profiles
            WHERE profiles.id = auth.uid()
                AND profiles.role = 'ADMIN'
        )
    );
-- Subscriptions: Only owner can see.
CREATE POLICY "Users can view own subscriptions" ON subscriptions FOR
SELECT USING (auth.uid() = user_id);
-- SEED DATA: Trash Vehicles
INSERT INTO trash_vehicles (
        name,
        capacity,
        price_ghs,
        description,
        icon,
        vehicle_type
    )
VALUES (
        'Tricycle Truck',
        'Small (2-3 bags)',
        40,
        'Ideal for narrow informal lanes.',
        '🛺',
        'TRICYCLE'
    ),
    (
        'Mini Truck',
        'Medium (Shop size)',
        85,
        'Perfect for markets and shops.',
        '🚛',
        'MINI_TRUCK'
    ),
    (
        'Large Trash Truck',
        'Large (Full Estate)',
        250,
        'Heavy-duty residential collection.',
        '🚚',
        'LARGE_TRUCK'
    );